version: '2'
services:
  zookeeper:
    image: zookeeper
    container_name: "zookeeper"
    ports:
      - "2181:2181"
  kafka:
    build: .
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: {hostname}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: kafkamanager/kafka-manager
    container_name: "kafka-manager"
    restart: always
    ports:
      - "9001:9000"
    environment:
      ZK_HOSTS: zookeeper
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_PASSWORD: "admin123"
